export enum ServerStatus {
  INIT = "INIT",
  ALLOCATING = "ALLOCATING",
  WAITING = "WAITING",
  IDLE = "IDLE",
  RUNNING = "RUNNING",
  CLOSING = "CLOSING",
  DEALLOCATING = "DEALLOCATING",
  CLOSED = "CLOSED",
  FAILED = "FAILED"
}